name: Busted
on: [push, pull_request]

defaults:
  run:
    working-directory: lua

jobs:
  sile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Unit Tests
        uses: lunarmodules/busted@v2.2.0
