name: Busted
on: [push, pull_request]
jobs:
  sile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Busted in ./lua
        run: |
           docker run -v $(pwd)/lua:/data ghcr.io/lunarmodules/busted:2.2.0
